name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.9"
        - "3.12"
        include:
          - python-version: "pypy-3.9"
            os: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64

      - name: "Install"
        run: pip install -q -r tests/requirements.txt && pip freeze --all

      - name: "Run tests for ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: python -m pytest --durations=10

      - name: Upload coverage to Codecov
        uses: "codecov/codecov-action@main"
